---
- name: Setup Deploye Server
  hosts: deploy-server
  become: true

  tasks:
    # Update system packages
    - name: Update apt package cache
      apt:
        update_cache: true

    - name: Upgrade system packages
      apt:
        upgrade: dist

    # Install Nginx
    - name: Install Nginx
      apt:
        name: ansible
        state: present

---
- name: Setup Jenkins
  hosts: jenkins
  become: true

  tasks:
    # Update system packages
    - name: Update apt package cache
      apt:
        update_cache: true

    - name: Upgrade system packages
      apt:
        upgrade: dist

    # Install Jenkins
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

---
- name: Setup Node Server
  hosts: node-server
  become: true

  tasks:
    # Update system packages
    - name: Update apt package cache
      apt:
        update_cache: true

    - name: Upgrade system packages
      apt:
        upgrade: dist

    # Install java
    - name: Install jdk-26
      apt:
        name: ansible
        state: present
