[ansible-master-controller]
ansible-controller ansible_host=44.211.169.196 ansible_user=ubuntu ansible_ssh_private_key_file=/home/kritesh/devops-class/my-aws-key-pair/key_pair_kritesh.pem

; [jenkins]
; jenkins-server ansible_host=3.84.23.29 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/key_pair_kritesh.pem

; [node-server-1]
; node-server-1 ansible_host=3.86.232.108 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/key_pair_kritesh.pem

; [node-server-2]
; node-server-2 ansible_host=3.85.171.87 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/key_pair_kritesh.pem